### ISSUE TITLE
Microscope Compatibility?

### ISSUE THREAD

**Issue by jess-burch** [niermann/temscript#10]
Hey there,

Was hoping to use this on a TFS Talos Arctica F200C but have been receiving a "ValueError: 2 is not a valid ProductFamily" that prevents me from using temscript.Microscope() or running any of the test scripts. Not sure if this wrapper is just not compatible with this scope or if there's another issue. Thank you!

Jess

**Comment by niermann** [comment]
Hi Jess,

thanks for reporting this issue. In principle the scripting adapter should work for your microscope. TFS/FEI added more and more functions to the TEM scripting with newer software versions and newer microscopes. To my knowledge they keep backward compatibility to older versions, thus all the functions implemented in temscript should still work. 

I've implemented temscript to work with our Titan Software version 1.1 microscope. It seems your Talos identifies itself as a newer ProductFamily, which is not (yet) known to temscript. I updated the temscript adapter in the Git repository to report your microscope as "FUTURE_2" instead of raising a ValueError. 

Can you try the new version ec3282a from the repository ? It it works, I will also upload a newer temscript version on PyPI (for easier installation). 

If you can send me the description of the ProductFamily enums values from your software, I can also include the Talos as Product Family. 

Regards,
Tore

**Comment by azazellochg** [comment]
TECNAI = 0
    TITAN = 1
    TALOS = 2

**Comment by niermann** [comment]
Thanks, Grigory

**Comment by niermann** [comment]
Closed, seems resolved
