### ISSUE TITLE
Any plan to add GoTowithSpeed ?

### ISSUE THREAD

**Issue by danielzt12** [niermann/temscript#7]
Hello, we are using your script to control our TEM(s), and it is excellent, thank you!
Do you have any plan to add GoTowithSpeed in the near future?
Thanks

**Comment by niermann** [comment]
Hi. Thanks for the appreciation.

I abstained from implementing GoToWithSpeed, since this function is available in the Interface but not documented in the manual (at least for Titan V1.1). As it seems to be documented in more recent Titan software versions (as I just discovered by a small websearch), I see no large problem of implementing it. I assume it is of interest for you, so I will add it in near future. 

Just a small unrelated survey: do you use the released binaries of temscript, or do you compile it on your own?

**Comment by danielzt12** [comment]
Dear Tore,
To answer your question, I compiled it on my own.
Thanks for helping out, I really appreciate that. 
To give some background info, I am a synchrotron beamline scientist in a group full of electron microscopists at the Center for Nanoscale Materials of Argonne National Laboratory. I am trying to help them with scripting their data analysis but also their data acquisition (which is when I came upon your github). We have installed your script (and the things I built based on your script) on three of our TEMs already, and all of our EM folks are very excited about the new capabilities.
One of the things we are trying to achieve is continuous scanning (hence the GoTowithSpeed). I found another library (https://pypi.org/project/instamatic/) that seems to do the job, but I guess it will take me quite some time to adapt it for python2 (some of our machines are pretty old). And because we are already building all our scripts around your temscript, I would really like to see it implemented with your API.
Thanks again for your help.
Best
Tao

**Comment by niermann** [comment]
Added in commit ba392b44dc32df839e38f2cf6f341d0dcb5bea97:
You can specify the keyword "speed" in the Illumination.GoTo() method (also to Microscope.set_stage_position). When "speed" is explicitly specified, GoTo() will use the GoToWithSpeed() method internally. This is also available in the 1.0.10 release.
